//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "cache")]
pub struct Model {
  #[sea_orm(primary_key, auto_increment = false)]
  pub id: Uuid,
  pub name: String,
  pub priority: i32,
  pub public: bool,
  pub quota: i64,
  pub public_signing_key: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
  #[sea_orm(has_many = "super::cache_access::Entity")]
  CacheAccess,
  #[sea_orm(has_many = "super::downstream_cache::Entity")]
  DownstreamCache,
  #[sea_orm(has_many = "super::nar_info::Entity")]
  NarInfo,
}

impl Related<super::cache_access::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::CacheAccess.def()
  }
}

impl Related<super::downstream_cache::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::DownstreamCache.def()
  }
}

impl Related<super::nar_info::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::NarInfo.def()
  }
}

impl ActiveModelBehavior for ActiveModel {}
