//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::sea_orm_active_enums::AccessType;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "cache_access")]
pub struct Model {
  #[sea_orm(primary_key)]
  pub id: i32,
  pub cache_id: Uuid,
  pub user_id: Option<Uuid>,
  pub group_id: Option<Uuid>,
  pub access_type: AccessType,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
  #[sea_orm(
    belongs_to = "super::cache::Entity",
    from = "Column::CacheId",
    to = "super::cache::Column::Id",
    on_update = "NoAction",
    on_delete = "Cascade"
  )]
  Cache,
  #[sea_orm(
    belongs_to = "super::group::Entity",
    from = "Column::GroupId",
    to = "super::group::Column::Id",
    on_update = "NoAction",
    on_delete = "Cascade"
  )]
  Group,
  #[sea_orm(
    belongs_to = "super::user::Entity",
    from = "Column::UserId",
    to = "super::user::Column::Id",
    on_update = "NoAction",
    on_delete = "Cascade"
  )]
  User,
}

impl Related<super::cache::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Cache.def()
  }
}

impl Related<super::group::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Group.def()
  }
}

impl Related<super::user::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::User.def()
  }
}

impl ActiveModelBehavior for ActiveModel {}
