//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "nar")]
pub struct Model {
  #[sea_orm(primary_key, auto_increment = false)]
  pub id: Uuid,
  pub hash: String,
  pub size: i64,
  pub nar_hash: String,
  pub nar_size: i64,
  pub created_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
  #[sea_orm(has_many = "super::nar_info::Entity")]
  NarInfo,
}

impl Related<super::nar_info::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::NarInfo.def()
  }
}

impl ActiveModelBehavior for ActiveModel {}
