//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "nar_info")]
pub struct Model {
  #[sea_orm(primary_key, auto_increment = false)]
  pub id: Uuid,
  pub cache_id: Uuid,
  pub nar_id: Uuid,
  pub store_path: String,
  pub compression: String,
  pub deriver: Option<String>,
  pub signature: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
  #[sea_orm(
    belongs_to = "super::cache::Entity",
    from = "Column::CacheId",
    to = "super::cache::Column::Id",
    on_update = "Cascade",
    on_delete = "Cascade"
  )]
  Cache,
  #[sea_orm(
    belongs_to = "super::nar::Entity",
    from = "Column::NarId",
    to = "super::nar::Column::Id",
    on_update = "Cascade",
    on_delete = "Cascade"
  )]
  Nar,
  #[sea_orm(has_many = "super::nar_info_reference::Entity")]
  NarInfoReference,
}

impl Related<super::cache::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Cache.def()
  }
}

impl Related<super::nar::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Nar.def()
  }
}

impl Related<super::nar_info_reference::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::NarInfoReference.def()
  }
}

impl ActiveModelBehavior for ActiveModel {}
