//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "user")]
pub struct Model {
  #[sea_orm(primary_key, auto_increment = false)]
  pub id: Uuid,
  pub name: String,
  pub email: String,
  pub password: String,
  pub salt: String,
  pub avatar: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
  #[sea_orm(has_many = "super::cache_access::Entity")]
  CacheAccess,
  #[sea_orm(has_many = "super::group_user::Entity")]
  GroupUser,
  #[sea_orm(has_many = "super::token::Entity")]
  Token,
}

impl Related<super::cache_access::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::CacheAccess.def()
  }
}

impl Related<super::group_user::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::GroupUser.def()
  }
}

impl Related<super::token::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Token.def()
  }
}

impl Related<super::group::Entity> for Entity {
  fn to() -> RelationDef {
    super::group_user::Relation::Group.def()
  }
  fn via() -> Option<RelationDef> {
    Some(super::group_user::Relation::User.def().rev())
  }
}

impl ActiveModelBehavior for ActiveModel {}
