// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type {
  AuthConfigData,
  AuthConfigErrors,
  AuthConfigResponses,
  AuthenticateData,
  AuthenticateErrors,
  CacheDetailsData,
  CacheDetailsErrors,
  CacheDetailsResponses,
  ClearCacheData,
  ClearCacheErrors,
  ClearCacheResponses,
  CompleteSetupData,
  CompleteSetupErrors,
  CreateCacheData,
  CreateCacheErrors,
  CreateCacheResponses,
  CreateGroupData,
  CreateGroupErrors,
  CreateGroupResponses,
  CreateTokenData,
  CreateTokenErrors,
  CreateTokenResponses,
  CreateUserData,
  CreateUserErrors,
  CreateUserResponses,
  DeleteCacheData,
  DeleteCacheErrors,
  DeleteCacheResponses,
  DeleteGroupData,
  DeleteGroupErrors,
  DeleteGroupResponses,
  DeletePathData,
  DeletePathErrors,
  DeletePathResponses,
  DeleteTokenData,
  DeleteTokenErrors,
  DeleteTokenResponses,
  DeleteUserData,
  DeleteUserErrors,
  DeleteUserResponses,
  EditCacheData,
  EditCacheErrors,
  EditCacheResponses,
  EditGroupData,
  EditGroupErrors,
  EditGroupResponses,
  EditTokenData,
  EditTokenErrors,
  EditTokenResponses,
  EditUserData,
  EditUserErrors,
  EditUserResponses,
  GetGeneralSettingsData,
  GetGeneralSettingsErrors,
  GetGeneralSettingsResponses,
  GetMailSettingsData,
  GetMailSettingsErrors,
  GetMailSettingsResponses,
  GetTokenData,
  GetTokenErrors,
  GetTokenResponses,
  GetUserSettingsData,
  GetUserSettingsErrors,
  GetUserSettingsResponses,
  GroupInfoData,
  GroupInfoErrors,
  GroupInfoResponses,
  InfoData,
  InfoErrors,
  InfoResponses,
  IsSetupData,
  IsSetupErrors,
  IsSetupResponses,
  KeyData,
  KeyResponses,
  ListCachesData,
  ListCachesErrors,
  ListCachesResponses,
  ListCachesSimple2Data,
  ListCachesSimple2Errors,
  ListCachesSimple2Responses,
  ListCachesSimpleData,
  ListCachesSimpleErrors,
  ListCachesSimpleResponses,
  ListGroupsData,
  ListGroupsErrors,
  ListGroupsResponses,
  ListGroupsSimpleData,
  ListGroupsSimpleErrors,
  ListGroupsSimpleResponses,
  ListTokensData,
  ListTokensErrors,
  ListTokensResponses,
  ListUsersData,
  ListUsersErrors,
  ListUsersResponses,
  ListUsersSimpleData,
  ListUsersSimpleErrors,
  ListUsersSimpleResponses,
  LogoutData,
  LogoutErrors,
  MailActiveData,
  MailActiveErrors,
  MailActiveResponses,
  NewCodeData,
  NewCodeResponses,
  OidcCallbackData,
  OidcCallbackErrors,
  OidcUrlData,
  OidcUrlErrors,
  ResetPasswordData,
  ResetPasswordErrors,
  ResetPasswordResponses,
  ResetUserAvatarData,
  ResetUserAvatarErrors,
  ResetUserAvatarResponses,
  ResetUserPasswordData,
  ResetUserPasswordErrors,
  ResetUserPasswordResponses,
  SaveMailSettingsData,
  SaveMailSettingsErrors,
  SaveMailSettingsResponses,
  SaveUserSettingsData,
  SaveUserSettingsErrors,
  SaveUserSettingsResponses,
  SearchStorePathsData,
  SearchStorePathsErrors,
  SearchStorePathsResponses,
  SendResetLinkData,
  SendResetLinkErrors,
  SendResetLinkResponses,
  TestData,
  TestErrors,
  TestMailData,
  TestMailErrors,
  TestMailResponses,
  TestResponses,
  TestTokenData,
  TokenInfoData,
  TokenInfoErrors,
  TokenInfoResponses,
  TokenRegenerateData,
  TokenRegenerateErrors,
  TokenRegenerateResponses,
  UpdateAccountData,
  UpdateAccountErrors,
  UpdateAccountResponses,
  UpdateAvatarData,
  UpdateAvatarErrors,
  UpdateAvatarResponses,
  UpdatePasswordData,
  UpdatePasswordErrors,
  UpdatePasswordResponses,
  UploadFinishData,
  UploadFinishErrors,
  UploadFinishResponses,
  UploadInfoData,
  UploadInfoErrors,
  UploadInfoResponses,
  UploadNarData,
  UploadNarErrors,
  UploadNarResponses,
  UploadPathData,
  UploadPathErrors,
  UploadPathResponses,
  UserInfoData,
  UserInfoErrors,
  UserInfoResponses
} from './types.gen';

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

export const isSetup = <ThrowOnError extends boolean = false>(
  options?: Options<IsSetupData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    IsSetupResponses,
    IsSetupErrors,
    ThrowOnError
  >({ url: '/api/setup', ...options });

export const completeSetup = <ThrowOnError extends boolean = false>(
  options: Options<CompleteSetupData, ThrowOnError>
) =>
  (options.client ?? client).post<unknown, CompleteSetupErrors, ThrowOnError>({
    url: '/api/setup',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const key = <ThrowOnError extends boolean = false>(
  options?: Options<KeyData, ThrowOnError>
) =>
  (options?.client ?? client).get<KeyResponses, unknown, ThrowOnError>({
    url: '/api/auth/password',
    ...options
  });

export const authenticate = <ThrowOnError extends boolean = false>(
  options: Options<AuthenticateData, ThrowOnError>
) =>
  (options.client ?? client).post<unknown, AuthenticateErrors, ThrowOnError>({
    url: '/api/auth/password',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const logout = <ThrowOnError extends boolean = false>(
  options?: Options<LogoutData, ThrowOnError>
) =>
  (options?.client ?? client).post<unknown, LogoutErrors, ThrowOnError>({
    url: '/api/auth/logout',
    ...options
  });

export const testToken = <ThrowOnError extends boolean = false>(
  options?: Options<TestTokenData, ThrowOnError>
) =>
  (options?.client ?? client).get<unknown, unknown, ThrowOnError>({
    url: '/api/auth/test_token',
    ...options
  });

export const oidcUrl = <ThrowOnError extends boolean = false>(
  options?: Options<OidcUrlData, ThrowOnError>
) =>
  (options?.client ?? client).get<unknown, OidcUrlErrors, ThrowOnError>({
    url: '/api/auth/oidc/url',
    ...options
  });

export const oidcCallback = <ThrowOnError extends boolean = false>(
  options: Options<OidcCallbackData, ThrowOnError>
) =>
  (options.client ?? client).get<unknown, OidcCallbackErrors, ThrowOnError>({
    url: '/api/auth/oidc/callback',
    ...options
  });

export const authConfig = <ThrowOnError extends boolean = false>(
  options?: Options<AuthConfigData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    AuthConfigResponses,
    AuthConfigErrors,
    ThrowOnError
  >({ url: '/api/auth/config', ...options });

export const updateAvatar = <ThrowOnError extends boolean = false>(
  options: Options<UpdateAvatarData, ThrowOnError>
) =>
  (options.client ?? client).post<
    UpdateAvatarResponses,
    UpdateAvatarErrors,
    ThrowOnError
  >({
    url: '/api/user/account/avatar',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const updatePassword = <ThrowOnError extends boolean = false>(
  options: Options<UpdatePasswordData, ThrowOnError>
) =>
  (options.client ?? client).post<
    UpdatePasswordResponses,
    UpdatePasswordErrors,
    ThrowOnError
  >({
    url: '/api/user/account/password',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const updateAccount = <ThrowOnError extends boolean = false>(
  options: Options<UpdateAccountData, ThrowOnError>
) =>
  (options.client ?? client).post<
    UpdateAccountResponses,
    UpdateAccountErrors,
    ThrowOnError
  >({
    url: '/api/user/account/update',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const info = <ThrowOnError extends boolean = false>(
  options?: Options<InfoData, ThrowOnError>
) =>
  (options?.client ?? client).get<InfoResponses, InfoErrors, ThrowOnError>({
    url: '/api/user/info',
    ...options
  });

export const deleteUser = <ThrowOnError extends boolean = false>(
  options: Options<DeleteUserData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    DeleteUserResponses,
    DeleteUserErrors,
    ThrowOnError
  >({
    url: '/api/user/management',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const listUsers = <ThrowOnError extends boolean = false>(
  options?: Options<ListUsersData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    ListUsersResponses,
    ListUsersErrors,
    ThrowOnError
  >({ url: '/api/user/management', ...options });

export const createUser = <ThrowOnError extends boolean = false>(
  options: Options<CreateUserData, ThrowOnError>
) =>
  (options.client ?? client).post<
    CreateUserResponses,
    CreateUserErrors,
    ThrowOnError
  >({
    url: '/api/user/management',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const editUser = <ThrowOnError extends boolean = false>(
  options: Options<EditUserData, ThrowOnError>
) =>
  (options.client ?? client).put<
    EditUserResponses,
    EditUserErrors,
    ThrowOnError
  >({
    url: '/api/user/management',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const userInfo = <ThrowOnError extends boolean = false>(
  options: Options<UserInfoData, ThrowOnError>
) =>
  (options.client ?? client).get<
    UserInfoResponses,
    UserInfoErrors,
    ThrowOnError
  >({ url: '/api/user/management/{uuid}', ...options });

export const mailActive = <ThrowOnError extends boolean = false>(
  options?: Options<MailActiveData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    MailActiveResponses,
    MailActiveErrors,
    ThrowOnError
  >({ url: '/api/user/management/mail', ...options });

export const listGroupsSimple = <ThrowOnError extends boolean = false>(
  options?: Options<ListGroupsSimpleData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    ListGroupsSimpleResponses,
    ListGroupsSimpleErrors,
    ThrowOnError
  >({ url: '/api/user/management/groups', ...options });

export const listCachesSimple = <ThrowOnError extends boolean = false>(
  options?: Options<ListCachesSimpleData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    ListCachesSimpleResponses,
    ListCachesSimpleErrors,
    ThrowOnError
  >({ url: '/api/user/management/caches', ...options });

export const resetUserAvatar = <ThrowOnError extends boolean = false>(
  options: Options<ResetUserAvatarData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    ResetUserAvatarResponses,
    ResetUserAvatarErrors,
    ThrowOnError
  >({
    url: '/api/user/management/avatar',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const resetUserPassword = <ThrowOnError extends boolean = false>(
  options: Options<ResetUserPasswordData, ThrowOnError>
) =>
  (options.client ?? client).put<
    ResetUserPasswordResponses,
    ResetUserPasswordErrors,
    ThrowOnError
  >({
    url: '/api/user/management/password',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const getGeneralSettings = <ThrowOnError extends boolean = false>(
  options?: Options<GetGeneralSettingsData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    GetGeneralSettingsResponses,
    GetGeneralSettingsErrors,
    ThrowOnError
  >({ url: '/api/settings/general', ...options });

export const getUserSettings = <ThrowOnError extends boolean = false>(
  options?: Options<GetUserSettingsData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    GetUserSettingsResponses,
    GetUserSettingsErrors,
    ThrowOnError
  >({ url: '/api/settings/user', ...options });

export const saveUserSettings = <ThrowOnError extends boolean = false>(
  options: Options<SaveUserSettingsData, ThrowOnError>
) =>
  (options.client ?? client).post<
    SaveUserSettingsResponses,
    SaveUserSettingsErrors,
    ThrowOnError
  >({
    url: '/api/settings/user',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const getMailSettings = <ThrowOnError extends boolean = false>(
  options?: Options<GetMailSettingsData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    GetMailSettingsResponses,
    GetMailSettingsErrors,
    ThrowOnError
  >({ url: '/api/settings/mail', ...options });

export const saveMailSettings = <ThrowOnError extends boolean = false>(
  options: Options<SaveMailSettingsData, ThrowOnError>
) =>
  (options.client ?? client).post<
    SaveMailSettingsResponses,
    SaveMailSettingsErrors,
    ThrowOnError
  >({
    url: '/api/settings/mail',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const sendResetLink = <ThrowOnError extends boolean = false>(
  options: Options<SendResetLinkData, ThrowOnError>
) =>
  (options.client ?? client).post<
    SendResetLinkResponses,
    SendResetLinkErrors,
    ThrowOnError
  >({
    url: '/api/mail/reset/send',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const resetPassword = <ThrowOnError extends boolean = false>(
  options: Options<ResetPasswordData, ThrowOnError>
) =>
  (options.client ?? client).post<
    ResetPasswordResponses,
    ResetPasswordErrors,
    ThrowOnError
  >({
    url: '/api/mail/reset/confirm',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const testMail = <ThrowOnError extends boolean = false>(
  options?: Options<TestMailData, ThrowOnError>
) =>
  (options?.client ?? client).post<
    TestMailResponses,
    TestMailErrors,
    ThrowOnError
  >({ url: '/api/mail/test', ...options });

export const deleteGroup = <ThrowOnError extends boolean = false>(
  options: Options<DeleteGroupData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    DeleteGroupResponses,
    DeleteGroupErrors,
    ThrowOnError
  >({
    url: '/api/group',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const listGroups = <ThrowOnError extends boolean = false>(
  options?: Options<ListGroupsData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    ListGroupsResponses,
    ListGroupsErrors,
    ThrowOnError
  >({ url: '/api/group', ...options });

export const createGroup = <ThrowOnError extends boolean = false>(
  options: Options<CreateGroupData, ThrowOnError>
) =>
  (options.client ?? client).post<
    CreateGroupResponses,
    CreateGroupErrors,
    ThrowOnError
  >({
    url: '/api/group',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const editGroup = <ThrowOnError extends boolean = false>(
  options: Options<EditGroupData, ThrowOnError>
) =>
  (options.client ?? client).put<
    EditGroupResponses,
    EditGroupErrors,
    ThrowOnError
  >({
    url: '/api/group',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const groupInfo = <ThrowOnError extends boolean = false>(
  options: Options<GroupInfoData, ThrowOnError>
) =>
  (options.client ?? client).get<
    GroupInfoResponses,
    GroupInfoErrors,
    ThrowOnError
  >({ url: '/api/group/{uuid}', ...options });

export const listUsersSimple = <ThrowOnError extends boolean = false>(
  options?: Options<ListUsersSimpleData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    ListUsersSimpleResponses,
    ListUsersSimpleErrors,
    ThrowOnError
  >({ url: '/api/group/users', ...options });

export const listCachesSimple2 = <ThrowOnError extends boolean = false>(
  options?: Options<ListCachesSimple2Data, ThrowOnError>
) =>
  (options?.client ?? client).get<
    ListCachesSimple2Responses,
    ListCachesSimple2Errors,
    ThrowOnError
  >({ url: '/api/group/caches', ...options });

export const newCode = <ThrowOnError extends boolean = false>(
  options?: Options<NewCodeData, ThrowOnError>
) =>
  (options?.client ?? client).post<NewCodeResponses, unknown, ThrowOnError>({
    url: '/api/cli',
    ...options
  });

export const getToken = <ThrowOnError extends boolean = false>(
  options: Options<GetTokenData, ThrowOnError>
) =>
  (options.client ?? client).put<
    GetTokenResponses,
    GetTokenErrors,
    ThrowOnError
  >({ url: '/api/cli', ...options });

export const deleteCache = <ThrowOnError extends boolean = false>(
  options: Options<DeleteCacheData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    DeleteCacheResponses,
    DeleteCacheErrors,
    ThrowOnError
  >({
    url: '/api/cache/management',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const listCaches = <ThrowOnError extends boolean = false>(
  options?: Options<ListCachesData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    ListCachesResponses,
    ListCachesErrors,
    ThrowOnError
  >({ url: '/api/cache/management', ...options });

export const createCache = <ThrowOnError extends boolean = false>(
  options: Options<CreateCacheData, ThrowOnError>
) =>
  (options.client ?? client).post<
    CreateCacheResponses,
    CreateCacheErrors,
    ThrowOnError
  >({
    url: '/api/cache/management',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const clearCache = <ThrowOnError extends boolean = false>(
  options: Options<ClearCacheData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    ClearCacheResponses,
    ClearCacheErrors,
    ThrowOnError
  >({ url: '/api/cache/management/{uuid}', ...options });

export const cacheDetails = <ThrowOnError extends boolean = false>(
  options: Options<CacheDetailsData, ThrowOnError>
) =>
  (options.client ?? client).get<
    CacheDetailsResponses,
    CacheDetailsErrors,
    ThrowOnError
  >({ url: '/api/cache/management/{uuid}', ...options });

export const editCache = <ThrowOnError extends boolean = false>(
  options: Options<EditCacheData, ThrowOnError>
) =>
  (options.client ?? client).post<
    EditCacheResponses,
    EditCacheErrors,
    ThrowOnError
  >({
    url: '/api/cache/management/{uuid}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const searchStorePaths = <ThrowOnError extends boolean = false>(
  options: Options<SearchStorePathsData, ThrowOnError>
) =>
  (options.client ?? client).post<
    SearchStorePathsResponses,
    SearchStorePathsErrors,
    ThrowOnError
  >({
    url: '/api/cache/management/{uuid}/search',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const deletePath = <ThrowOnError extends boolean = false>(
  options: Options<DeletePathData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    DeletePathResponses,
    DeletePathErrors,
    ThrowOnError
  >({
    url: '/api/cache/management/{uuid}/path',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const uploadInfo = <ThrowOnError extends boolean = false>(
  options: Options<UploadInfoData, ThrowOnError>
) =>
  (options.client ?? client).post<
    UploadInfoResponses,
    UploadInfoErrors,
    ThrowOnError
  >({
    url: '/api/cache/push/info',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const uploadPath = <ThrowOnError extends boolean = false>(
  options: Options<UploadPathData, ThrowOnError>
) =>
  (options.client ?? client).post<
    UploadPathResponses,
    UploadPathErrors,
    ThrowOnError
  >({
    url: '/api/cache/push',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const uploadNar = <ThrowOnError extends boolean = false>(
  options: Options<UploadNarData, ThrowOnError>
) =>
  (options.client ?? client).post<
    UploadNarResponses,
    UploadNarErrors,
    ThrowOnError
  >({ url: '/api/cache/push/{uuid}', ...options });

export const uploadFinish = <ThrowOnError extends boolean = false>(
  options: Options<UploadFinishData, ThrowOnError>
) =>
  (options.client ?? client).put<
    UploadFinishResponses,
    UploadFinishErrors,
    ThrowOnError
  >({
    url: '/api/cache/push/{uuid}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const test = <ThrowOnError extends boolean = false>(
  options?: Options<TestData, ThrowOnError>
) =>
  (options?.client ?? client).get<TestResponses, TestErrors, ThrowOnError>({
    url: '/api/cache/test',
    ...options
  });

export const deleteToken = <ThrowOnError extends boolean = false>(
  options: Options<DeleteTokenData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    DeleteTokenResponses,
    DeleteTokenErrors,
    ThrowOnError
  >({
    url: '/api/token',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const listTokens = <ThrowOnError extends boolean = false>(
  options?: Options<ListTokensData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    ListTokensResponses,
    ListTokensErrors,
    ThrowOnError
  >({ url: '/api/token', ...options });

export const createToken = <ThrowOnError extends boolean = false>(
  options: Options<CreateTokenData, ThrowOnError>
) =>
  (options.client ?? client).post<
    CreateTokenResponses,
    CreateTokenErrors,
    ThrowOnError
  >({
    url: '/api/token',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const editToken = <ThrowOnError extends boolean = false>(
  options: Options<EditTokenData, ThrowOnError>
) =>
  (options.client ?? client).put<
    EditTokenResponses,
    EditTokenErrors,
    ThrowOnError
  >({
    url: '/api/token',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });

export const tokenInfo = <ThrowOnError extends boolean = false>(
  options: Options<TokenInfoData, ThrowOnError>
) =>
  (options.client ?? client).get<
    TokenInfoResponses,
    TokenInfoErrors,
    ThrowOnError
  >({ url: '/api/token/{uuid}', ...options });

export const tokenRegenerate = <ThrowOnError extends boolean = false>(
  options: Options<TokenRegenerateData, ThrowOnError>
) =>
  (options.client ?? client).post<
    TokenRegenerateResponses,
    TokenRegenerateErrors,
    ThrowOnError
  >({ url: '/api/token/{uuid}', ...options });
