// This file is auto-generated by @hey-api/openapi-ts

import type {
  ListTokensResponse,
  SearchStorePathsResponse,
  TokenInfoResponse
} from './types.gen';

const searchResultSchemaResponseTransformer = (data: any) => {
  data.created_at = new Date(data.created_at);
  if (data.last_accessed_at) {
    data.last_accessed_at = new Date(data.last_accessed_at);
  }
  return data;
};

export const searchStorePathsResponseTransformer = async (
  data: any
): Promise<SearchStorePathsResponse> => {
  data = data.map((item: any) => searchResultSchemaResponseTransformer(item));
  return data;
};

const tokenInfoSchemaResponseTransformer = (data: any) => {
  data.exp = new Date(data.exp);
  if (data.last_used) {
    data.last_used = new Date(data.last_used);
  }
  return data;
};

export const listTokensResponseTransformer = async (
  data: any
): Promise<ListTokensResponse> => {
  data = data.map((item: any) => tokenInfoSchemaResponseTransformer(item));
  return data;
};

export const tokenInfoResponseTransformer = async (
  data: any
): Promise<TokenInfoResponse> => {
  data = tokenInfoSchemaResponseTransformer(data);
  return data;
};
