name: 'Cli Release'

on:
  release:
    types:
      - published
  pull_request:

jobs:
  release-artifacts:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        name:
          - linux-x86-64-gnu
          - linux-x86-64-musl
          - linux-arm64-gnu
          - linux-arm64-musl
          - windows-x86-64
          - windows-arm64
          - macos-x86-64
          - macos-arm64
        include:
          - name: linux-x86-64-gnu
            target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            cross: false
          - name: linux-x86-64-musl
            target: x86_64-unknown-linux-musl
            os: ubuntu-latest
            cross: true
          - name: linux-arm64-gnu
            target: aarch64-unknown-linux-gnu
            os: ubuntu-24.04-arm
            cross: false
          - name: linux-arm64-musl
            target: aarch64-unknown-linux-musl
            os: ubuntu-24.04-arm
            cross: true
          - name: windows-x86-64
            target: x86_64-pc-windows-msvc
            os: windows-latest
            cross: false
          - name: windows-arm64
            target: aarch64-pc-windows-msvc
            os: windows-latest
            cross: true
          - name: macos-x86-64
            target: x86_64-apple-darwin
            os: macos-latest
            cross: false
          - name: macos-arm64
            target: aarch64-apple-darwin
            os: macos-latest
            cross: false
    name: Build and Release Cli for ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Cache cargo and rust files
        id: rust_cache
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
          shared-key: 'cli_release_cache-${{ matrix.name }}'
      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          target: ${{ matrix.target }}
          toolchain: stable
      - name: Install cross
        if: matrix.cross == 'true'
        run: cargo install cross --locked
      - name: Build
        run: ${{ matrix.cross == 'true' && 'cross' || 'cargo' }} build --release --locked --target ${{ matrix.target }} -p hibernation
