name: Create Release

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  create-release-tag:
    if: ${{ github.event_name == 'pull_request' && github.event.pull_request.merged && contains(github.event.pull_request.labels.*.name, 'release-version') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
        uses: actions/checkout@v6

      - name: Create tag
        run: |
          VERSION=${{ github.event.pull_request.head.ref }}
          VERSION=${VERSION#chore/release-version-}
          echo "Creating tag for version $VERSION"
          git tag "$VERSION"
          git push origin "$VERSION"

      - name: Update latest tag
        run: |
          git tag -f latest
          git push origin -f latest

      - name: Update major tag
        run: |
          VERSION=${{ github.event.pull_request.head.ref }}
          VERSION=${VERSION#chore/release-version-}
          MAJOR_VERSION=$(echo $VERSION | cut -d. -f1)
          git tag -f "$MAJOR_VERSION"
          git push origin -f "$MAJOR_VERSION"
