name: Flake Build

on:
  pull_request:
  release:
    types:
      - published

jobs:
  flake-build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - ubuntu-24.04-arm
          - macos-latest
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: cachix/install-nix-action@v31
      - name: Install Hibernation CLI
        uses: profiidev/hibernation@v0
        if: github.event_name != 'pull_request'
        with:
          url: ${{ secrets.HIBERNATION_URL }}
          token: ${{ secrets.HIBERNATION_TOKEN }}
          signing-key: ${{ secrets.HIBERNATION_SIGNING_KEY }}

      - name: Run build
        run: nix build . -Lv --print-out-paths --accept-flake-config

      - name: Cache results
        if: github.event_name != 'pull_request'
        run: hibernation push projects $(readlink result)
