name: Test Setup Action
on:
  pull_request:

jobs:
  test-setup:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - ubuntu-24.04-arm
          - macos-latest
        version:
          - v0.1.0
          - latest
    name: Test Setup Action on ${{ matrix.os }} with version ${{ matrix.version }}
    steps:
      - uses: actions/checkout@v6
      - name: Setup Cli
        uses: ./
        with:
          version: ${{ matrix.version }}
          url: https://cache.example.com
          token: test1234
          signing-key: test5678

      - name: Verify Installation
        if: matrix.version != 'latest'
        run: |
          RAW_VERSION=${{ matrix.version }}
          VERSION="${RAW_VERSION#v}"
          hibernation --version | grep $VERSION

      - name: Verify Latest Installation
        if: matrix.version == 'latest'
        run: |
          hibernation --version

      - name: Verify Signing Key
        run: |
          echo $HIBERNATION_SIGNING_KEY | grep "test5678"
